### ISSUE TITLE
Move to resque org?

### ISSUE THREAD

**Issue by iloveitaly** [resque/resque-pool#208]
Hello! Curious if there's any interest in moving this repo to the @resque org. I've been trying to get more of the resque extensions in a single place to make it easier for folks to find & contribute to popular extensions.

What do you think?

**Comment by nevans** [comment]
Sorry for the slow reply.  I'm all for it! :)  Just let me know how and where to coordinate.

**Comment by iloveitaly** [comment]
@nevans followed up via email!

**Comment by nevans** [comment]
I think this can be closed now.  Thanks, @iloveitaly! 🙂
